language: cpp
dist: trusty

compiler:
  - clang
  - gcc

install:
  - curl https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.0.57.0/linux/vulkansdk-linux-x86_64-1.0.57.0.run
  - ./vulkansdk-linux-x86_64-1.0.57.0.run

script: echo "Foo"
